name: Modified Rocks

on:
  workflow_call:
    outputs:
        rocks:
            description: List of modified rocks as a json string.
            value: ${{ jobs.modifiedrocks.outputs.rocks }}


jobs:
  modifiedrocks:
    runs-on: ubuntu-latest
    outputs:
      rocks: ${{ steps.changed-rocks.outputs.rocks }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get changed rockcraft files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            rocks/*/rockcraft.yaml
      - name: set output
        id: changed-rocks
        run: |
          components=()
          # trim file name to component name
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              component=$(echo $file | sed 's/rocks\/\(\S.*\)\/rockcraft.yaml/\1/')
              [[ ! -z "$component" ]] && components+=($component)
          done
          modified_rocks=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${components[@]}")
          echo "Modified rocks: $modified_rocks"
          echo "rocks=$modified_rocks" >> $GITHUB_OUTPUT
